class TeleTwoMain:
    CONNECT_HEADER_BUTTON = "xpath=//button[text()='ПОДКЛЮЧИТЬСЯ']"
    CONNECT_FUTER_BUTTON = "xpath=(//button[@id='btnup'])[3]"
    NAME_INPUT = "xpath=(//input[@name='Name'])[1]"
    NAME_INPUT_TWO = "xpath=(//input[@name='Name'])[2]"
    PHONE_INPUT_FIRST = "xpath=(//input[@name='Phone'])[1]"
    PHONE_INPUT = "xpath=(//input[@name='Phone'])[2]"
    PHONE_INPUT_THREE = "xpath=(//input[@name='Phone'])[3]"
    SEND_BUTTON = "xpath=(//input[@value='Отправить'])[1]"
    SEND_BUTTON_TWO = "xpath=(//input[@value='Отправить'])[2]"
    BANNER_BUTTON = "xpath=(//button[text()='ПОДКЛЮЧИТЬ'])"
    TARIFF_CARDS = "xpath=(//div[@class='uc-BLOCK-MOBILE']//div[@id='sale'])"
    TARIFF_MOB = "xpath=(//div[@class='uc-BLOCK-KONVERGENT']//div[@id='sale'])"
    TARIFF_BUTTON = "xpath=(//div[@itemprop='offers'])"
    CITY_INPUT = "xpath=//input[@placeholder='Город']"
    STREET_INPUT = "xpath=//input[@placeholder='Улица']"
    CHECK_THE_ADDRESS = "xpath=//input[@value='Проверить адрес']"
    BUTTON_DONT_CITY = "xpath=//button[@class='region-search__button']"

